name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install autotools
      run: sudo apt install automake libtool
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install autotools
      run: brew install automake autoconf libtool
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-mingw:
    runs-on: windows-2025
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install autotools
      run: pacman -S base-devel
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
